### ISSUE TITLE
Allow stakers to crowdfund their stake

### ISSUE THREAD

**Issue by SamAg19** [razor-network/oracle-contracts#815]
We have minSafeRazor which staker must satisfy while staking in the smart contracts but no one can delegate to the staker due activity checks being done on the staker. `epochLastRevealed` will be initially 0 for the staker

https://github.com/razor-network/contracts/blob/f7d482f79930c7a9cc81ae80c4bf9abfbc4ceec0/contracts/Core/StakeManager.sol#L671

**Comment by SkandaBhat** [comment]
Assumption: Staker should be able to stake less than min stake and rely on delegation (crowdfunding) to fulfill min stake - Wrong

1. Staker stakes min safe razor
2. Staker accepts delegation from others
3. Once Staker’s stake > minstake, Staker proceeds with voting.

If Staker falls below mistake but higher than minsafe razor
1. If Staker within grace period, they can accept delegation
2. If Staker outside of grace period, they cannot accept delegation

If new Staker stakes < minstake  and > minsafe razor
1. They cannot accept delegation (because they are inactive)
2. They cannot participate in voting (because stake < minstake)

If Staker gets penalised/slashed
1. If slashed, then they cannot participate in the network anymore or accept delegation.
2. If penalty to < minstake but  they can still accept delegation within grace period
